# Generated by Django 3.0.6 on 2020-05-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='job',
            name='placeholder',
        ),
        migrations.AddField(
            model_name='job',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
